<?php

return [
    "Apple",
    "Samsung",
    "Nike",
    "Adidas",
    "Toyota",
    "BMW",
    "Mercedes-Benz",
    "Sony",
    "Panasonic",
    "Google",
    "Microsoft",
    "Amazon",
    "Facebook (Meta)",
    "Tesla",
    "L'Oréal",
    "P&G",
    "McDonald's",
    "Coca-Cola",
    "PepsiCo",
    "Starbucks",
    "Unilever",
    "Nestlé",
    "Louis Vuitton",
    "Gucci",
    "Hermès",
    "Tiffany & Co.",
    "Rolex",
    "Dior",
    "Chanel",
    "Prada",
    "Ferrari",
    "Lamborghini",
    "Puma",
    "Levi's",
    "H&M",
    "Zara",
    "Ralph Lauren",
    "Burberry",
    "Oakley",
    "Ray-Ban",
    "Timberland",
    "Under Armour",
    "Calvin Klein",
    "Versace",
    "Diesel",
    "Guess",
    "Tommy Hilfiger",
    "Hugo Boss",
    "Giorgio Armani",
    "Michael Kors",
    "Coach",
    "Kate Spade",
    "LG",
    "Hisense",
    "Sharp",
    "Philips",
    "Bose",
    "JBL",
    "Sennheiser",
    "Logitech",
    "Dell",
    "HP",
    "Lenovo",
    "ASUS",
    "Acer",
    "Intel",
    "AMD",
    "Nvidia",
    "Qualcomm",
    "Canon",
    "Nikon",
    "Fujifilm"
];
