<?php

return [
    'Eletrônicos',
    'Roupas e Acessórios',
    'Casa e Jardim',
    'Beleza e Saúde',
    'Esportes e Lazer',
    'Brinquedos e Jogos',
    'Automotivo',
    'Livros e Papelaria',
    'Alimentos e Bebidas',
    'Ferramentas e Materiais de Construção',
    'Informática e Acessórios',
    'Móveis e Decoração',
    'Relógios e Joias',
    'Produtos para Animais',
    'Outros',
    'Moda Masculina',
    'Moda Feminina',
    'Moda Infantil',
    'Calçados',
    'Acessórios para Celulares',
    'Equipamentos de Informática',
    'Câmeras e Acessórios',
    'Eletrodomésticos',
    'Eletroportáteis',
    'Produtos de Limpeza',
    'Produtos de Cuidado Pessoal',
    'Saúde e Bem-Estar',
    'Suplementos Alimentares',
    'Artigos Esportivos',
    'Equipamentos de Camping e Pesca',
    'Instrumentos Musicais',
    'Artigos de Festa'
];